name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
  # test master every day at 05:00 UTC
  # (mathcomp/mathcomp-dev is rebuilt every day at 04:00 Paris time)
    - cron: '0 5 * * *'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - mathcomp/mathcomp:1.13.0-coq-8.12
          - mathcomp/mathcomp:1.13.0-coq-8.13
          - mathcomp/mathcomp:1.13.0-coq-8.14
          - mathcomp/mathcomp:1.14.0-coq-8.13
          - mathcomp/mathcomp:1.14.0-coq-8.14
          - mathcomp/mathcomp:1.14.0-coq-8.15
          - mathcomp/mathcomp:1.15.0-coq-8.13
          - mathcomp/mathcomp:1.15.0-coq-8.14
          - mathcomp/mathcomp:1.15.0-coq-8.15
          - mathcomp/mathcomp:1.15.0-coq-8.16
          - mathcomp/mathcomp-dev:coq-8.14
          - mathcomp/mathcomp-dev:coq-8.15
          - mathcomp/mathcomp-dev:coq-8.16
          - mathcomp/mathcomp-dev:coq-dev
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-mathcomp-odd-order.opam'
          custom_image: ${{ matrix.image }}
